/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeloRouteImport } from './routes/velo'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as InfosRouteImport } from './routes/infos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CombinesRouteImport } from './routes/combines'
import { Route as CanoeRouteImport } from './routes/canoe'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccesRouteImport } from './routes/acces'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin.stock'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminActivitiesRouteImport } from './routes/_authenticated/admin.activities'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VeloRoute = VeloRouteImport.update({
  id: '/velo',
  path: '/velo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosRoute = InfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinesRoute = CombinesRouteImport.update({
  id: '/combines',
  path: '/combines',
  getParentRoute: () => rootRouteImport,
} as any)
const CanoeRoute = CanoeRouteImport.update({
  id: '/canoe',
  path: '/canoe',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesRoute = AccesRouteImport.update({
  id: '/acces',
  path: '/acces',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivitiesRoute =
  AuthenticatedAdminActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/canoe': typeof CanoeRoute
  '/combines': typeof CombinesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/infos': typeof InfosRoute
  '/reservation': typeof ReservationRoute
  '/velo': typeof VeloRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acces': typeof AccesRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/canoe': typeof CanoeRoute
  '/combines': typeof CombinesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/infos': typeof InfosRoute
  '/reservation': typeof ReservationRoute
  '/velo': typeof VeloRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acces': typeof AccesRoute
  '/auth': typeof AuthRoute
  '/avis': typeof AvisRoute
  '/canoe': typeof CanoeRoute
  '/combines': typeof CombinesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/infos': typeof InfosRoute
  '/reservation': typeof ReservationRoute
  '/velo': typeof VeloRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/activities': typeof AuthenticatedAdminActivitiesRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acces'
    | '/auth'
    | '/avis'
    | '/canoe'
    | '/combines'
    | '/contact'
    | '/faq'
    | '/infos'
    | '/reservation'
    | '/velo'
    | '/admin'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/stock'
    | '/admin/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acces'
    | '/auth'
    | '/avis'
    | '/canoe'
    | '/combines'
    | '/contact'
    | '/faq'
    | '/infos'
    | '/reservation'
    | '/velo'
    | '/admin/activities'
    | '/admin/bookings'
    | '/admin/stock'
    | '/admin'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acces'
    | '/auth'
    | '/avis'
    | '/canoe'
    | '/combines'
    | '/contact'
    | '/faq'
    | '/infos'
    | '/reservation'
    | '/velo'
    | '/_authenticated/admin'
    | '/_authenticated/admin/activities'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesRoute: typeof AccesRoute
  AuthRoute: typeof AuthRoute
  AvisRoute: typeof AvisRoute
  CanoeRoute: typeof CanoeRoute
  CombinesRoute: typeof CombinesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InfosRoute: typeof InfosRoute
  ReservationRoute: typeof ReservationRoute
  VeloRoute: typeof VeloRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/velo': {
      id: '/velo'
      path: '/velo'
      fullPath: '/velo'
      preLoaderRoute: typeof VeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos': {
      id: '/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof InfosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combines': {
      id: '/combines'
      path: '/combines'
      fullPath: '/combines'
      preLoaderRoute: typeof CombinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canoe': {
      id: '/canoe'
      path: '/canoe'
      fullPath: '/canoe'
      preLoaderRoute: typeof CanoeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acces': {
      id: '/acces'
      path: '/acces'
      fullPath: '/acces'
      preLoaderRoute: typeof AccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activities': {
      id: '/_authenticated/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivitiesRoute: typeof AuthenticatedAdminActivitiesRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivitiesRoute: AuthenticatedAdminActivitiesRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesRoute: AccesRoute,
  AuthRoute: AuthRoute,
  AvisRoute: AvisRoute,
  CanoeRoute: CanoeRoute,
  CombinesRoute: CombinesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InfosRoute: InfosRoute,
  ReservationRoute: ReservationRoute,
  VeloRoute: VeloRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
